### PR TITLE
Can't figure out slider :( Milestone05

### PR DESCRIPTION
**Pull request by HJMcSorley**
I am so stuck on the analytics slider. 
I can't figure out how to place the slider below the plot or make it dynamic (so all around, I'm just not really getting it).

@jimmyliu1326 any pro tips?

### CODE REVIEW

**Comment by jimmyliu1326** [comment]
hey Hannah, why not just place the slider below the dropdown_x/dropdown_y in the bottom sidebar?

The slider is to change the axes limits right?

**Comment by HJMcSorley** [comment]
Yes, that's right it's to change the axes limits. Good idea, I'll try it in the sidebar I didn't even think of that. Sorry!

**Comment by jimmyliu1326** [comment]
Don't worry about it haha its kinda tricky to have the sliders actually because the limits of the slider might have to depend on the variables selected in the dropdown. But I will take a look later tonight.

**Comment by jimmyliu1326** [comment]
Also, I think it might make more sense to restrict the x-axis to only be categorical variables, and y-axis to have continuous variables and then just make boxplots? Because some of the plots look kind of strange haha (e.g. picking Sex vs. Race), but then if we do this, there's really no point of having a slider to adjust axis for boxplots

**Comment by jimmyliu1326** [comment]
Alternatively, we can restrict the analytics plot to only have continuous variables (Years of edu, age, net gain, work hours) and color the points by categorical variables? This way we can still have the sliders.

**Comment by HJMcSorley** [comment]
Hey Jimmy! Yeah, I think limiting the analytics plot to continuous/numerical variables will make the most sense for x-vs-y comparisons with a slider. I thought we could do a radio button for sex (male/female) and I like the idea of colouring points by categorical variable!

**Pull request merged**
